### ISSUE TITLE
Unable to start BLED112 dongle using adapter.start()

### ISSUE THREAD

**Issue by sbhurji** [peplin/pygatt#119]
Hi,

I have used the BLED112 dongle on a different PC and didn't face this issue but I needed to set up a new computer with pygatt and ran into issues. I was trying to execute the following code which has worked for me in the past but for some reason the following code kept giving me an error:

```
import pygatt

adapter = pygatt.BGAPIBackend(serial_port = "COM4")
print adapter._serial_port
try:
    adapter.start()
    devices = adapter.scan()
    print devices
    device = adapter.connect('88:6b:0f:2f:65:d6')
    print device
    value = device.char_read("a1e8f5b1-696b-4e4c-87c6-69dfe0b0093b")
except:
    print "Failed"
finally:
    adapter.stop()
```

```
Traceback (most recent call last):
  File "D:\App1.py", line 18, in <module>
    adapter.stop()
  File "C:\Python27\lib\site-packages\pygatt\backends\bgapi\bgapi.py", line 218, in stop
    if self._running.is_set():
AttributeError: 'NoneType' object has no attribute 'is_set'

```
I had confirmed that the COM port number was correct before running my code but it looked like the script could never find the port. Looking at issue #118 I saw that the author had success by modifying bgapi.py by adding a delay in the adapter.start() function. Since I was not having much luck I decided to try this out as well and found that by adding a 1 second delay before self._open_serial_port() fixed my issue. 

        self.send_command(CommandBuilder.system_reset(0))
        self._ser.flush()
        self._ser.close()
        **time.sleep(1)**
        self._open_serial_port()
        self._receiver = threading.Thread(target=self._receive)
        self._receiver.daemon = True

While this is currently working for me, I would like to know if this is a common issue for people using Windows 10 and/or using the BLED112 with a USB 3.0 port.

**Comment by amias-channer** [comment]
this was an issue for me on OSX Sierra (mbp with usb-c)  using pygatt installed via pip , adding this pause made it work for me.

**Comment by chrisabbott** [comment]
This worked on El Capitan as well! Thanks

**Comment by peplin** [comment]
This is fixed by #144 - there was a bug in the automatic connection retry logic.

**Comment by kevincurtiss** [comment]
Still not fixed, have latest version from repo but had to add sleep(1). On OSX

**Comment by peplin** [comment]
Please provide the debug log - see the README for instructions on how to
enable it. I don't have Windows or OS X machine, and I've unfortunately
been unable to reproduce this issue in Linux. I need all of your help here!

**Comment by kevincurtiss** [comment]
Interesting enough I got to work this morning and took out the sleep() trying to reproduce it and it wasn't happening. I'll try and repro and get a log for you.

**Comment by kevincurtiss** [comment]
Here's a log. Interesting enough it seems somewhat related to whether my Macbook Pro is plugged into external power. Not plugged in it happens generally, plugged in it's fine.
[log.txt](https://github.com/peplin/pygatt/files/1388153/log.txt)

**Comment by amias-channer** [comment]
Hello all,

My experience of this is that it is extra latency caused by the USBC
implementation on 2017 mbp.

It seems to always effect the first try and sometimes the second.

It could be related to the the fact that USBC routes power over the same
bus and this might create a delay in settling the USB links.  I would
recommend powering the laptop directly from usb and comparing results for
when it's powered via the USBC port on the adapter (mine was USBC to usb a
+ hdmi + USBC).

Cheers
Amias

**Comment by kevincurtiss** [comment]
Just to clarify, I have a 2015 MBP without USB-C but there does appear to be some sort of timing issue.
